### ISSUE TITLE
FXP project compilation

### ISSUE THREAD

**Issue by anike94** [ni/niveristand-scan-engine-fxp-libraries#6]
After I downloaded the zip file I try to compile the FXP LabVIEW project but when I opened the project there were a lot of missing VI (Please find the attached screenshot
![screenshot 5](https://user-images.githubusercontent.com/45994641/50587870-a01a9480-0ea5-11e9-8b10-8c21a9837d0e.png)
)
If I try to open any VI it searches for the file but I am not able to find those VI'S in the downloaded file
![image](https://user-images.githubusercontent.com/45994641/50587916-cb04e880-0ea5-11e9-9547-c5aff9657d6b.png)
Can anyone please let me know how to resolve this issue
Thank You

**Comment by TamonP** [comment]
I have exactly the same problem as of 2019/5/30. Can a dev comment on this issue and how to resolve it?
@keprt @rtzoeller

**Comment by rtzoeller** [comment]
Run `Script FXP Read.vi` and `Script FXP Write.vi` to completion. They will generate the files, at which the build should succeed.
